### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by danfike** [jwatte/node-mersenne#5]
Hi Jon, do you think you could add a `LICENSE` to this repo and update the `npm` package? I'd love to use this for some work stuff, but policy prevents me from doing so while no license is defined. 

Courtesy Links:
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by danfike** [comment]
Actually, I can see now the 3-clause BSD license directly in `mersenne.js`. I should be able to get by with that, but you might want to consider creating a `LICENSE` file anyways. GitHub's features are pretty robust now when such files exist:

![image](https://cloud.githubusercontent.com/assets/8999918/25360287/1efb1434-290e-11e7-8b72-21ca2750239b.png)

**Comment by jwatte** [comment]
Thanks for pointing out the missing file.
You could just have sent a pull request ;-)
I'll see if I can find my old npm password somewhere.

Sincerely,

jw





Sincerely,

Jon Watte


--
"I find that the harder I work, the more luck I seem to have." -- Thomas
Jefferson

**Comment by danfike** [comment]
I actually thought about just putting together a PR, but when I first filed this, I actually didn't notice the license in `mersenne.js` yet, and I really didn't want to be presumptuous and select a license on your behalf to use in a PR.

But I did consider just picking the one I want, making the PR, and seeing what happens. :D

**Comment by jwatte** [comment]
Fortune favors the bold!
Anyway, I published version 0.0.4, which is the same as 0.0.3 except has a
LICENSE file and license: field in the package.json.
Good luck with your project!

Sincerely,

jw





Sincerely,

Jon Watte


--
"I find that the harder I work, the more luck I seem to have." -- Thomas
Jefferson

**Comment by danfike** [comment]
Thanks a ton, Jon! 

I'm closing this Issue.
